### ISSUE TITLE
Can't make to work with catch-all routing - [...page].astro

### ISSUE THREAD

**Issue by CarloBu** [florian-lefebvre/astro-i18n-test#19]
I really like the DX experience, but I can't make it work with catch-all routing for pagination, like "\routes\blog\ [...page].astro"
Is it just me or current i18n does not support this?

**Comment by florian-lefebvre** [comment]
Hi, happy you like the package so far! It's indeed not supported just yet (see https://astro-i18n.netlify.app/getting-started/known-issues/#rest-parameters), you can subscribe to #2 to know when it's released! Just note it's not in my priorities, I have a few issues I need to address first

**Comment by CarloBu** [comment]
Thank you for your response. At this time, the pagination feature isn't a priority for me, so I plan to consider its implementation after you solve it.  This is a cool stuff you do, Internationalizing websites can be quite challenging to do it right and it's wonderful that you offer a solution for free. Thank you again for your efforts!

**Comment by florian-lefebvre** [comment]
Thank you so much! Feel free to open an issue for any little bug, possible enhancement or docs that can be improved!
