### ISSUE TITLE
Take trailing slash into account

### ISSUE THREAD

**Issue by florian-lefebvre** [florian-lefebvre/astro-i18n-test#24]

**Comment by nojaf** [comment]
Hi there, shot in the dark, but right now I don't get my language when I browser to `/fr` only when I go to `/fr/`.

![image](https://github.com/astrolicious/i18n/assets/2621499/89d46a01-6d49-4183-be9c-35fd388d7c35)

Would this related to this bug?

**Comment by florian-lefebvre** [comment]
mmh I'm not sure because you don't have a special `trailingSlash` configuration. Would you mind providing a minimal reproduction? (in a repository, there are issues with Stackblitz)

**Comment by nojaf** [comment]
<strike>This is what I have so far: https://github.com/nojaf/astro-translations-repro</strike>

**Comment by dsijakovski98** [comment]
Having the same issue, cannot get locales to load for `/mk` only for `/mk/`.
Also, looks like it is the same behaviour in the [Demo app](https://astro-i18n-demo.netlify.app/fr/).

If can be made so that it recognizes the locale without the trailing slash, would be awesome 🙏

**Comment by amosbastian** [comment]
Same as above. It only loads the default locale's translations if you have `trailingSlash` set to e.g. `never`. Would be great to get this fixed 🙏

**Comment by florian-lefebvre** [comment]
If someone wants to contribute this fix, please do! I don't have near plans to address it

**Comment by nojaf** [comment]
Sounds reasonable, any pointers or steps on how one would debug or run this locally?
