### ISSUE TITLE
String Interpolation?

### ISSUE THREAD

**Issue by bertPB** [florian-lefebvre/astro-i18n-test#41]
I can't seem to find it in the docs or examples, but is there a way to use string interpolation with this package?
For example to include html tags or dynamic values inside the translation.

Thanks

**Comment by florian-lefebvre** [comment]
I think what you're requesting is the same as #11? If so feel free to close this issue! FYI I'm not actively working on this integration mainly because of lack of time

**Comment by bertPB** [comment]
Ah yes, is indeed the same issue.
But I just figured out a different way to solve my specific issue (using @html in svelte), so this can be closed.

Thanks for taking the time to respond

**Comment by florian-lefebvre** [comment]
Glad you found a solution!
